(function () {
    const DATA = {
        Honduras: [
            "Atlántida",
            "Choluteca",
            "Colón",
            "Comayagua",
            "Copán",
            "Cortés",
            "El Paraíso",
            "Francisco Morazán",
            "Gracias a Dios",
            "Intibucá",
            "Islas de la Bahía",
            "La Paz",
            "Lempira",
            "Ocotepeque",
            "Olancho",
            "Santa Bárbara",
            "Valle",
            "Yoro",
        ],
        Guatemala: [
            "Alta Verapaz",
            "Baja Verapaz",
            "Chimaltenango",
            "Chiquimula",
            "El Progreso",
            "Escuintla",
            "Guatemala",
            "Huehuetenango",
            "Izabal",
            "Jalapa",
            "Jutiapa",
            "Petén",
            "Quetzaltenango",
            "Quiché",
            "Retalhuleu",
            "Sacatepéquez",
            "San Marcos",
            "Santa Rosa",
            "Sololá",
            "Suchitepéquez",
            "Totonicapán",
            "Zacapa",
        ],
        Nicaragua: [
            "Boaco",
            "Carazo",
            "Chinandega",
            "Chontales",
            "Estelí",
            "Granada",
            "Jinotega",
            "León",
            "Madriz",
            "Managua",
            "Masaya",
            "Matagalpa",
            "Nueva Segovia",
            "Rivas",
            "Río San Juan",
            "RACCN",
            "RACCS",
        ],
        "El Salvador": [
            "Ahuachapán",
            "Cabañas",
            "Chalatenango",
            "Cuscatlán",
            "La Libertad",
            "La Paz",
            "La Unión",
            "Morazán",
            "San Miguel",
            "San Salvador",
            "San Vicente",
            "Santa Ana",
            "Sonsonate",
            "Usulután",
        ],
        "Costa Rica": [
            "San José",
            "Alajuela",
            "Cartago",
            "Heredia",
            "Guanacaste",
            "Puntarenas",
            "Limón",
        ],
        Panamá: [
            "Bocas del Toro",
            "Chiriquí",
            "Coclé",
            "Colón",
            "Darién",
            "Herrera",
            "Los Santos",
            "Panamá",
            "Panamá Oeste",
            "Veraguas",
            "Guna Yala",
            "Ngäbe-Buglé",
            "Emberá-Wounaan",
            "Guna de Madungandí",
            "Guna de Wargandí",
            "Naso Tjër Di",
        ],
        Belice: [
            "Corozal",
            "Orange Walk",
            "Belize",
            "Cayo",
            "Stann Creek",
            "Toledo",
        ],
    };

    const CITIES = {
        Honduras: {
            Atlántida: [
                "La Ceiba",
                "El Porvenir",
                "San Francisco",
                "Tela",
                "Arizona",
                "Esparta",
                "Jutiapa",
                "La Masica",
                "La Unión",
                "San Antonio",
                "Iriona",
            ],
            Choluteca: [
                "Choluteca",
                "Apacilagua",
                "Concepción de María",
                "Duyure",
                "El Corpus",
                "El Triunfo",
                "Marcovia",
                "Morolica",
                "Namasigüe",
                "Orocuina",
                "Pespire",
                "San Antonio de Flores",
                "San Isidro",
                "San José",
                "San Marcos de Colón",
                "Santa Ana de Yusguare",
                "Santa Cruz",
                "San Pablo",
            ],
            Colón: [
                "Trujillo",
                "Balfate",
                "Iriona",
                "Limón",
                "Sabá",
                "Santa Fe",
                "Sonaguera",
                "Tocoa",
                "Bonito Oriental",
                "Santos Guardiola",
                "Tumbador",
            ],
            Comayagua: [
                "Comayagua",
                "Siguatepeque",
                "La Libertad",
                "Taulabé",
                "San José de Comayagua",
                "Ajuterique",
                "Lamaní",
                "Lejamaní",
                "Esquías",
                "Ojos de Agua",
                "Las Lajas",
                "El Rosario",
                "Humuya",
                "El Llano",
                "La Trinidad",
                "San Jerónimo",
                "Meámbar",
            ],
            Copán: [
                "Santa Rosa de Copán",
                "Copán Ruinas",
                "Cucuyagua",
                "Dolores",
                "Dulce Nombre",
                "El Paraíso",
                "Florida",
                "La Jigua",
                "La Entrada",
                "La Unión",
                "Nueva Arcadia",
                "San Agustín",
                "San Antonio",
                "San Jerónimo",
                "San José",
                "San Nicolás",
                "San Pedro",
                "San Sebastián",
                "Santa Rita",
            ],
            Cortés: [
                "San Pedro Sula",
                "Puerto Cortés",
                "Choloma",
                "La Lima",
                "Villanueva",
                "Omoa",
                "Santa Cruz de Yojoa",
                "Pimienta",
                "San Manuel",
                "Potrerillos",
                "San Antonio de Cortés",
                "San Francisco de Yojoa",
            ],
            "El Paraíso": [
                "Danlí",
                "Yuscarán",
                "El Paraíso",
                "Trojes",
                "Texiguat",
                "Morocelí",
                "Oropolí",
                "Potrerillos",
                "Vado Ancho",
                "Alauca",
                "Jacaleapa",
                "Liure",
                "Pafe",
                "Teupasenti",
                "Soledad",
                "Villa de San Antonio",
            ],
            "Francisco Morazán": [
                "Tegucigalpa",
                "Comayagüela",
                "Valle de Ángeles",
                "Santa Lucía",
                "Talanga",
                "Sabanagrande",
                "La Laguna",
                "Lepaterique",
                "Tatumbla",
                "Cedros",
                "Alubaren",
                "El Porvenir",
                "Maraita",
                "San Ignacio",
                "Guaimaca",
                "Reitoca",
                "San Buenaventura",
            ],
            "Gracias a Dios": [
                "Puerto Lempira",
                "Ahuas",
                "Brus Laguna",
                "Juan Francisco Bulnes",
                "Wampusirpi",
                "Mocorón",
                "Rus Rus",
            ],
            Intibucá: [
                "La Esperanza",
                "Intibucá",
                "Jesús de Otoro",
                "San Miguel Guancapla",
                "San Juan",
                "Camasca",
                "San Antonio",
                "Yamaranguila",
            ],
            "Islas de la Bahía": [
                "Roatán",
                "Utila",
                "Guanaja",
                "José Santos Guardiola",
            ],
            "La Paz": [
                "La Paz",
                "Marcala",
                "San José",
                "Santa Elena",
                "Guanajiquil",
                "Santa María",
                "Cabañas",
                "San Pedro",
                "San Antonio",
                "Zacapa",
            ],
            Lempira: [
                "Gracias",
                "Erandique",
                "La Campa",
                "La Iguala",
                "San Marcos de Caiquín",
                "San Manuel Colohete",
                "San Sebastián",
                "San Juan Guarita",
                "San Rafael",
                "La Unión",
                "Piraera",
                "Mapulaca",
                "La Virtud",
                "Tambla",
                "Valladolid",
                "Concepción",
                "Gualcinse",
            ],
            Ocotepeque: [
                "Ocotepeque",
                "Nuevo Ocotepeque",
                "Santa Fe",
                "San Marcos",
                "La Encarnación",
                "Sinuapa",
                "Belén Gualcho",
                "San Francisco del Valle",
            ],
            Olancho: [
                "Juticalpa",
                "Catacamas",
                "Salamá",
                "Gualaco",
                "Manto",
                "Guarizama",
                "Patuca",
                "Dulce Nombre",
                "Campamento",
                "El Rosario",
                "Jano",
                "La Unión",
                "San Francisco de Becerra",
            ],
            "Santa Bárbara": [
                "Santa Bárbara",
                "Quimistán",
                "Nueva Frontera",
                "Trinidad",
                "San Vicente Centenario",
                "San Luis",
                "San Nicolás",
                "El Níspero",
                "San Jerónimo",
                "Magdalena",
            ],
            Valle: [
                "Nacaome",
                "San Lorenzo",
                "Goascorán",
                "Alianza",
                "Aramecina",
                "Caridad",
                "Santa Ana",
            ],
            Yoro: [
                "Yoro",
                "El Progreso",
                "Olanchito",
                "Victoria",
                "Santa Rita",
                "Sulaco",
                "Yorito",
                "Morales",
                "Llera",
                "Pueblo Nuevo",
                "El Negrito",
            ],
        },
        Guatemala: {
            "Alta Verapaz": [
                "Cobán",
                "Santa Cruz Verapaz",
                "San Cristóbal Verapaz",
                "Tactic",
                "Tamahú",
                "Tucurú",
                "Panzós",
                "Senahú",
                "San Pedro Carchá",
                "Santa Catalina La Tinta",
                "Raxruhá",
                "Chisec",
                "Fray Bartolomé de las Casas",
                "Lanquín",
            ],
            "Baja Verapaz": [
                "Salamá",
                "San Miguel Chicaj",
                "Rabinal",
                "Cubulco",
                "Granados",
                "Santa Cruz El Chol",
                "Purulhá",
            ],
            Chimaltenango: [
                "Chimaltenango",
                "San José Poaquil",
                "San Martín Jilotepeque",
                "Comalapa",
                "Santa Apolonia",
                "Tecpán Guatemala",
                "Patzún",
                "Pochuta",
                "Patzicía",
                "Santa Cruz Balanyá",
                "Acatenango",
                "Yepocapa",
                "San Andrés Itzapa",
                "Parramos",
                "Zaragoza",
                "El Tejar",
            ],
            Chiquimula: [
                "Chiquimula",
                "San José La Arada",
                "San Juan Ermita",
                "Jocotán",
                "Camotán",
                "Olopa",
                "Esquipulas",
                "Concepción Las Minas",
                "Quezaltepeque",
                "San Jacinto",
                "Ipala",
            ],
            "El Progreso": [
                "Guastatoya",
                "Morazán",
                "San Agustín Acasaguastlán",
                "San Cristóbal Acasaguastlán",
                "El Jícaro",
                "Sansare",
                "Sanarate",
                "San Antonio La Paz",
            ],
            Escuintla: [
                "Escuintla",
                "Santa Lucía Cotzumalguapa",
                "La Democracia",
                "Siquinalá",
                "Masagua",
                "Tiquisate",
                "La Gomera",
                "Guanagazapa",
                "San José",
                "Iztapa",
                "Palín",
                "San Vicente Pacaya",
                "Nueva Concepción",
            ],
            Guatemala: [
                "Guatemala City",
                "Santa Catarina Pinula",
                "San José Pinula",
                "San José del Golfo",
                "Palencia",
                "Chinautla",
                "San Pedro Ayampuc",
                "Mixco",
                "San Pedro Sacatepéquez",
                "San Juan Sacatepéquez",
                "San Raymundo",
                "Chuarrancho",
                "Fraijanes",
                "Amatitlán",
                "Villa Nueva",
                "Villa Canales",
                "San Miguel Petapa",
            ],
            Huehuetenango: [
                "Huehuetenango",
                "Chiantla",
                "Malacatancito",
                "Cuilco",
                "Nentón",
                "San Pedro Necta",
                "Jacaltenango",
                "Soloma",
                "Ixtahuacán",
                "Santa Bárbara",
                "La Libertad",
                "La Democracia",
                "San Miguel Acatán",
                "San Rafael La Independencia",
                "Todos Santos Cuchumatán",
                "San Juan Atitán",
                "Santa Eulalia",
                "San Mateo Ixtatán",
                "Colotenango",
                "San Sebastián Huehuetenango",
                "Tectitán",
                "Concepción Huista",
                "San Juan Ixcoy",
                "San Antonio Huista",
                "San Sebastián Coatán",
                "Barillas",
                "Aguacatán",
                "San Rafael Petzal",
                "San Gaspar Ixchil",
                "Santiago Chimaltenango",
                "Santa Ana Huista",
            ],
            Izabal: [
                "Puerto Barrios",
                "Livingston",
                "El Estor",
                "Morales",
                "Los Amates",
            ],
            Jalapa: [
                "Jalapa",
                "San Pedro Pinula",
                "San Luis Jilotepeque",
                "San Manuel Chaparrón",
                "San Carlos Alzatate",
                "Monjas",
                "Mataquescuintla",
            ],
            Jutiapa: [
                "Jutiapa",
                "El Progreso",
                "Santa Catarina Mita",
                "Agua Blanca",
                "Asunción Mita",
                "Yupiltepeque",
                "Atescatempa",
                "Jerez",
                "El Adelanto",
                "Zapotitlán",
                "Comapa",
                "Jalpatagua",
                "Conguaco",
                "Moyuta",
                "Pasaco",
                "Quesada",
            ],
            Petén: [
                "Flores",
                "San José",
                "San Benito",
                "San Andrés",
                "La Libertad",
                "San Francisco",
                "Santa Ana",
                "Dolores",
                "San Luis",
                "Sayaxché",
                "Melchor de Mencos",
                "Poptún",
            ],
            Quetzaltenango: [
                "Quetzaltenango",
                "Salcajá",
                "Olintepeque",
                "San Carlos Sija",
                "Sibilia",
                "Cabricán",
                "Cajolá",
                "San Miguel Sigüilá",
                "Ostuncalco",
                "San Mateo",
                "Concepción Chiquirichapa",
                "San Martín Sacatepéquez",
                "Almolonga",
                "Cantel",
                "Huitán",
                "Zunil",
                "Colomba",
                "San Francisco La Unión",
                "El Palmar",
                "Coatepeque",
                "Génova",
                "Flores Costa Cuca",
                "La Esperanza",
            ],
            Quiché: [
                "Santa Cruz del Quiché",
                "Chiché",
                "Chinique",
                "Zacualpa",
                "Chajul",
                "Santo Tomás Chichicastenango",
                "Patzité",
                "San Antonio Ilotenango",
                "San Pedro Jocopilas",
                "Cunén",
                "San Juan Cotzal",
                "Joyabaj",
                "Nebaj",
                "San Andrés Sajcabajá",
                "Uspantán",
                "Sacapulas",
                "San Bartolomé Jocotenango",
                "Canillá",
                "Chicamán",
                "Pachalum",
            ],
            Retalhuleu: [
                "Retalhuleu",
                "San Sebastián",
                "Santa Cruz Muluá",
                "San Martín Zapotitlán",
                "San Felipe",
                "San Andrés Villa Seca",
                "Champerico",
                "Nuevo San Carlos",
                "El Asintal",
            ],
            Sacatepéquez: [
                "Antigua Guatemala",
                "Jocotenango",
                "Pastores",
                "Sumpango",
                "Santo Domingo Xenacoj",
                "Santiago Sacatepéquez",
                "San Bartolomé Milpas Altas",
                "San Lucas Sacatepéquez",
                "Santa Lucía Milpas Altas",
                "Magdalena Milpas Altas",
                "Santa María de Jesús",
                "Ciudad Vieja",
                "San Miguel Dueñas",
                "Alotenango",
                "San Antonio Aguas Calientes",
                "Santa Catarina Barahona",
            ],
            "San Marcos": [
                "San Marcos",
                "San Pedro Sacatepéquez",
                "San Antonio Sacatepéquez",
                "Comitancillo",
                "San Miguel Ixtahuacán",
                "Concepción Tutuapa",
                "Tacaná",
                "Sibinal",
                "Tajumulco",
                "Tejutla",
                "San Rafael Pie de la Cuesta",
                "Nuevo Progreso",
                "El Tumbador",
                "San José El Rodeo",
                "Malacatán",
                "Catarina",
                "Ayutla",
                "Ocós",
                "San Pablo",
                "El Quetzal",
                "La Reforma",
                "Pajapita",
                "Ixchiguán",
                "San José Ojetenam",
                "San Cristóbal Cucho",
                "Esquipulas Palo Gordo",
                "Río Blanco",
                "San Lorenzo",
            ],
            "Santa Rosa": [
                "Cuilapa",
                "Barberena",
                "Santa Rosa de Lima",
                "Casillas",
                "San Rafael Las Flores",
                "Oratorio",
                "San Juan Tecuaco",
                "Chiquimulilla",
                "Taxisco",
                "Santa María Ixhuatán",
                "Guazacapán",
                "Santa Cruz Naranjo",
                "Pueblo Nuevo Viñas",
                "Nueva Santa Rosa",
            ],
            Sololá: [
                "Sololá",
                "San José Chacayá",
                "Santa María Visitación",
                "Santa Lucía Utatlán",
                "Nahualá",
                "Santa Catarina Ixtahuacán",
                "Santa Clara La Laguna",
                "Concepción",
                "San Andrés Semetabaj",
                "Panajachel",
                "Santa Catarina Palopó",
                "San Antonio Palopó",
                "San Lucas Tolimán",
                "Santa Cruz La Laguna",
                "San Pablo La Laguna",
                "San Marcos La Laguna",
                "San Juan La Laguna",
                "San Pedro La Laguna",
                "Santiago Atitlán",
            ],
            Suchitepéquez: [
                "Mazatenango",
                "Cuyotenango",
                "San Francisco Zapotitlán",
                "San Bernardino",
                "San José El Ídolo",
                "Santo Domingo Suchitepéquez",
                "San Lorenzo",
                "Samayac",
                "San Pablo Jocopilas",
                "San Antonio Suchitepéquez",
                "San Miguel Panán",
                "San Gabriel",
                "Chicacao",
                "Patulul",
                "Santa Bárbara",
                "San Juan Bautista",
                "Santo Tomás La Unión",
                "Zunilito",
                "Pueblo Nuevo",
                "Río Bravo",
            ],
            Totonicapán: [
                "Totonicapán",
                "San Cristóbal Totonicapán",
                "San Francisco El Alto",
                "San Andrés Xecul",
                "Momostenango",
                "Santa María Chiquimula",
                "Santa Lucía La Reforma",
                "San Bartolo",
            ],
            Zacapa: [
                "Zacapa",
                "Estanzuela",
                "Río Hondo",
                "Gualán",
                "Teculután",
                "Usumatlán",
                "Cabañas",
                "San Diego",
                "La Unión",
                "Huité",
            ],
        },
        "El Salvador": {
            Ahuachapán: [
                "Ahuachapán",
                "Apaneca",
                "Concepción de Ataco",
                "Tacuba",
                "Guaymango",
                "Jujutla",
                "San Francisco Menéndez",
                "San Pedro Puxtla",
            ],
            Cabañas: [
                "Sensuntepeque",
                "Ilobasco",
                "Jutiapa",
                "Tejutepeque",
                "Dolores",
                "Guacotecti",
                "San Isidro",
                "Victoria",
            ],
            Chalatenango: [
                "Chalatenango",
                "Comalapa",
                "La Laguna",
                "Las Flores",
                "Nombre de Dios",
                "Nueva Trinidad",
                "Ojos de Agua",
                "Potonico",
                "San Antonio Los Ranchos",
                "San Fernando",
                "San Ignacio",
                "San Isidro Labrador",
                "San José Cancasque",
                "San Luis del Carmen",
                "San Miguel de Mercedes",
                "San Rafael",
                "Santa Rita",
                "Tejutla",
            ],
            Cuscatlán: ["Cojutepeque", "Suchitoto", "Candelaria", "Corozal"],
            "La Libertad": [
                "Santa Tecla",
                "Antiguo Cuscatlán",
                "Nuevo Cuscatlán",
                "La Libertad",
                "Quezaltepeque",
                "Zaragoza",
                "Lourdes",
                "El Tunco",
                "El Zonte",
            ],
            "La Paz": [
                "Zacatecoluca",
                "Olocuilta",
                "San Luis Talpa",
                "Santiago Nonualco",
                "Tapalhuaca",
                "San Juan Nonualco",
                "San Pedro Masahuat",
                "San Antonio Masahuat",
                "El Rosario",
                "San Juan Talpa",
                "San Luis La Herradura",
            ],
            Morazán: [
                "San Francisco Gotera",
                "Perquín",
                "Jocoro",
                "Delicias de Concepción",
                "Cacaopera",
                "San Fernando",
                "Yamabal",
                "San Simón",
                "El Divisadero",
            ],
            "San Miguel": [
                "San Miguel",
                "Chinameca",
                "Moncagua",
                "San Jorge",
                "El Tránsito",
                "Quelepa",
                "Nuevo Edén de San Juan",
                "San Antonio",
                "Chapeltique",
                "El Sauce",
                "El Tamarindo",
            ],
            "San Salvador": [
                "San Salvador",
                "Soyapango",
                "Mejicanos",
                "Ilopango",
                "Apopa",
                "Ayutuxtepeque",
                "Cuscatancingo",
                "Ciudad Delgado",
                "El Paisnal",
                "Guazapa",
                "Nejapa",
                "Panchimalco",
                "Rosario de Mora",
                "San Marcos",
                "San Martín",
                "Santiago Texacuangos",
                "Santo Tomás",
                "Tonacatepeque",
            ],
            "San Vicente": [
                "San Vicente",
                "Apastepeque",
                "Tecoluca",
                "Guadalupe",
                "San Esteban Catarina",
                "Santa Clara",
                "San Sebastián",
                "San Cayetano Istepeque",
            ],
            "Santa Ana": [
                "Santa Ana",
                "Metapán",
                "Chalchuapa",
                "Candelaria de la Frontera",
                "El Congo",
                "Masahuat",
                "San Sebastián Salitrillo",
                "San Antonio Pajonal",
            ],
            Sonsonate: [
                "Sonsonate",
                "Acajutla",
                "Nahuilingo",
                "Armenia",
                "Santo Domingo",
                "Izalco",
                "Nahuizalco",
                "Salcoatitán",
                "Santa Catarina Masahuat",
                "San Antonio del Monte",
                "San Julián",
                "San Sebastián Salitrillo",
            ],
            Usulután: [
                "Usulután",
                "Jiquilisco",
                "Santiago de María",
                "Berlín",
                "Conchagua",
                "El Triunfo",
                "Ereguayquín",
                "Estanzuelas",
                "Jucuapa",
                "La Unión",
                "Nueva Granada",
                "Puerto El Triunfo",
            ],
            "La Unión": [
                "La Unión",
                "Santa Rosa de Lima",
                "Conchagua",
                "El Carmen",
                "Intipucá",
                "El Sauce",
                "La Ceiba",
                "Pasaquina",
                "Polorós",
                "San Alejo",
            ],
        },
        "Costa Rica": {
            "San José": [
                "San José",
                "Escazú",
                "Desamparados",
                "Puriscal",
                "Tarrazú",
                "Aserrí",
                "Mora",
                "Goicoechea",
                "Santa Ana",
                "Alajuelita",
                "Montes de Oca",
                "Curridabat",
                "Dota",
                "Perez Zeledon",
                "León XIII",
            ],
            Alajuela: [
                "Alajuela",
                "San Ramón",
                "Grecia",
                "San Mateo",
                "Atenas",
                "Naranjo",
                "Palmares",
                "Poás",
                "Orotina",
                "San Carlos",
                "Zarcero",
                "Valverde Vega",
                "Upala",
                "Los Chiles",
                "Guatuso",
            ],
            Cartago: [
                "Cartago",
                "Paraíso",
                "Jiménez",
                "Turrialba",
                "Alvarado",
                "Oreamuno",
                "El Guarco",
            ],
            Heredia: [
                "Heredia",
                "Barva",
                "Santo Domingo",
                "Santa Bárbara",
                "San Rafael",
                "San Isidro",
                "Belén",
                "Flores",
                "San Pablo",
                "Sarapiquí",
            ],
            Guanacaste: [
                "Liberia",
                "Nicoya",
                "Santa Cruz",
                "Bagaces",
                "Carrillo",
                "Nandayure",
                "La Cruz",
                "Hojancha",
            ],
            Puntarenas: [
                "Puntarenas",
                "Esparza",
                "Buenos Aires",
                "Montes de Oro",
                "Osa",
                "Quepos",
                "Golfito",
                "Coto Brus",
                "Parrita",
                "Corredores",
                "Garabito",
            ],
            Limón: [
                "Limón",
                "Pococí",
                "Siquirres",
                "Talamanca",
                "Matina",
                "Guácimo",
            ],
        },
        Belice: {
            Corozal: [
                "Corozal Town",
                "Chunox",
                "Calcutta",
                "Chowk",
                "Patchakan",
            ],
            "Orange Walk": [
                "Orange Walk Town",
                "San Estevan",
                "Yo Creek",
                "Albion",
                "Trial Farm",
            ],
            Belize: [
                "Belize City",
                "Ladyville",
                "Burrell Boom",
                "San Pedro",
                "San Pablo",
            ],
            Cayo: [
                "Belmopan",
                "San Ignacio",
                "Santa Elena",
                "Benque Viejo del Carmen",
                "Succotz",
            ],
            "Stann Creek": [
                "Dangriga",
                "Placencia",
                "Hopkins",
                "Sarawina",
                "Santa Cruz",
            ],
            Toledo: [
                "Punta Gorda",
                "Monkey River",
                "San Pedro Columbia",
                "Big Falls",
                "San Antonio",
            ],
        },
        Panamá: {
            "Bocas del Toro": [
                "Bocas del Toro",
                "Changuinola",
                "Chiriquí Grande",
                "Almirante",
            ],
            Chiriquí: [
                "David",
                "Boquete",
                "Dolega",
                "Gualaca",
                "Bugaba",
                "Renacimiento",
                "Tierras Altas",
                "Tolé",
                "Barú",
            ],
            Coclé: [
                "Penonomé",
                "Aguadulce",
                "Antón",
                "Natá",
                "La Pintada",
                "Olá",
            ],
            Colón: ["Colón", "Chagres", "Donoso", "Portobelo", "Santa Isabel"],
            Darien: ["La Palma", "Pinogana", "Chepigana"],
            Herrera: [
                "Chitré",
                "Las Minas",
                "Parita",
                "Ocú",
                "La Villa de Los Santos",
                "Los Pozos",
                "Macaracas",
            ],
            "Los Santos": [
                "Las Tablas",
                "Pedasí",
                "Guararé",
                "Tonosí",
                "Los Santos",
                "Mariato",
                "Macaracas",
            ],
            Panamá: [
                "Panamá",
                "San Miguelito",
                "La Chorrera",
                "Arraiján",
                "Balboa",
                "Ancón",
            ],
            "Panamá Oeste": [
                "La Chorrera",
                "Arraiján",
                "Capira",
                "San Carlos",
                "Chame",
            ],
            Veraguas: [
                "Santiago",
                "Atalaya",
                "Soná",
                "Río de Jesús",
                "San Francisco",
                "Mariato",
                "Cañazas",
                "La Mesa",
            ],
            "Guna Yala": ["Guna Yala"],
            "Ngäbe-Buglé": [
                "Kankintú",
                "Mironó",
                "Ñürüm",
                "Müna",
                "Kusapín",
                "Jirondai",
                "Nole Duima",
                "Santa Catalina",
            ],
            "Emberá-Wounaan": ["Cémaco", "Sambú"],
        },
        Nicaragua: {
            Boaco: [
                "Boaco",
                "Camoapa",
                "San José de los Remates",
                "Santa Lucía",
                "Teustepe",
            ],
            Carazo: [
                "Jinotepe",
                "Diriamba",
                "Dolores",
                "La Conquista",
                "Santa Teresa",
                "San Marcos",
            ],
            Chinandega: [
                "Chinandega",
                "El Viejo",
                "Corinto",
                "Chichigalpa",
                "Posoltega",
                "Puerto Morazán",
            ],
            Chontales: [
                "Juigalpa",
                "Santo Tomás",
                "Acoyapa",
                "Comalapa",
                "La Libertad",
                "San Francisco de Cuapa",
            ],
            Estelí: [
                "Estelí",
                "Condega",
                "San Juan de Limay",
                "La Trinidad",
                "Pueblo Nuevo",
            ],
            Granada: [
                "Granada",
                "Nandaime",
                "Diría",
                "Diriomo",
                "Nicolás Ruíz",
                "San Juan de Oriente",
            ],
            Jinotega: [
                "Jinotega",
                "San Rafael del Norte",
                "San Sebastián de Yalí",
                "La Concordia",
                "Santa María de Pantasma",
            ],
            León: [
                "León",
                "Nagarote",
                "La Paz Centro",
                "El Jicaral",
                "Quezalguaque",
                "Telica",
            ],
            Madriz: [
                "Somoto",
                "Palacagüina",
                "Yalagüina",
                "San José de Cusmapa",
                "Las Sabanas",
                "Totogalpa",
            ],
            Managua: [
                "Managua",
                "Tipitapa",
                "Ciudad Sandino",
                "Ticuantepe",
                "Mateare",
                "San Rafael del Sur",
            ],
            Masaya: [
                "Masaya",
                "Nindirí",
                "Ticuantepe",
                "Nandasmo",
                "La Concepción",
                "Masatepe",
            ],
            Matagalpa: [
                "Matagalpa",
                "Sébaco",
                "Río Blanco",
                "San Ramón",
                "Esquipulas",
                "San Dionisio",
            ],
            "Nueva Segovia": [
                "Ocotal",
                "Jalapa",
                "Dipilto",
                "Mozonte",
                "San Fernando",
                "Santa María",
            ],
            Rivas: [
                "Rivas",
                "San Jorge",
                "Belen",
                "Potosí",
                "Altagracia",
                "Cárdenas",
            ],
            "Río San Juan": [
                "San Carlos",
                "El Castillo",
                "San Miguelito",
                "Morrito",
                "Los Chiles",
            ],
            RACCN: [
                "Bilwi (Puerto Cabezas)",
                "Waspam",
                "Rosita",
                "Puerto Lempira",
                "Awas Tingni",
            ],
            RACCS: [
                "Bluefields",
                "Laguna de Perlas",
                "Kukra Hill",
                "Corn Island",
                "Little Corn Island",
            ],
        },

        Panamá: {
            "Bocas del Toro": [
                "Bocas del Toro (Isla Colón)",
                "Changuinola",
                "Almirante",
            ],
            Chiriquí: ["David", "Boquete", "Bugaba"],
            Coclé: ["Penonomé", "Aguadulce", "Antón"],
            Colón: ["Colón", "Portobelo", "Sabanitas"],
            Darién: ["La Palma", "Yaviza", "Garachiné"],
            Herrera: ["Chitré", "Parita", "Las Minas"],
            "Los Santos": ["Las Tablas", "Guararé", "Pedasí"],
            Panamá: ["Ciudad de Panamá", "San Miguelito", "Tocumen"],
            "Panamá Oeste": ["La Chorrera", "Arraiján", "Capira"],
            Veraguas: ["Santiago", "Soná", "Atalaya"],
            "Guna Yala": ["El Porvenir", "Cartí", "Playón Chico"],
            "Ngäbe-Buglé": ["Llano Tugrí (Buäbidí)", "Kankintú", "Chichica"],
            "Emberá-Wounaan": ["Unión Chocó", "Sambú", "Cirilo Guainora"],
            "Guna de Madungandí": ["Aguas Claras", "Ibedí", "Ipetí Guna"],
            "Guna de Wargandí": ["Mortí", "Nurra", "Wala"],
            "Naso Tjër Di": ["Sieyik", "Bonyic", "Sieykin"],
        },
        Belice: {
            Corozal: ["Corozal Town", "Consejo Shores", "Sarteneja"],
            "Orange Walk": ["Orange Walk Town", "Trial Farm", "Shipyard"],
            Belize: ["Belize City", "San Pedro", "Ladyville"],
            Cayo: ["Belmopan", "San Ignacio", "Santa Elena"],
            "Stann Creek": ["Dangriga", "Placencia", "Hopkins"],
            Toledo: ["Punta Gorda", "Big Falls", "San Antonio"],
        },
    };

    function normalize(str) {
        return (str || "")
            .toString()
            .trim()
            .toLowerCase()
            .normalize("NFD")
            .replace(/\p{Diacritic}/gu, "");
    }

    function getByPaisName(nombrePais) {
        if (!nombrePais) return [];
        if (DATA[nombrePais]) return DATA[nombrePais].slice();
        const n = normalize(nombrePais);
        for (const key of Object.keys(DATA)) {
            if (normalize(key) === n) return DATA[key].slice();
        }
        return [];
    }

    function getCitiesByPaisDep(nombrePais, nombreDepartamento) {
        if (!nombrePais || !nombreDepartamento) return [];
        const find = (obj, key) => {
            if (obj[key]) return obj[key];
            const n = normalize(key);
            for (const k of Object.keys(obj)) {
                if (normalize(k) === n) return obj[k];
            }
            return null;
        };
        const byPais = find(CITIES, nombrePais);
        if (!byPais) return [];
        const byDep = find(byPais, nombreDepartamento);
        return Array.isArray(byDep) ? byDep.slice() : [];
    }

    try {
        window.subdivisionHelper = {
            getByPaisName,
            getCitiesByPaisDep,
            listCountries() {
                return Object.keys(DATA).slice();
            },
        };
    } catch (_) {}
})();
